### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Experilux** [Valks-Bots/partner-bot#19] opened 2020-10-05 16:00 UTC
When I try to bump a server, it is giving me an error. The ad has no emojis,links, or anything like that and is very short. How can I fix this?

**Comment by Experilux** [comment] 2020-10-05 16:02
Only 1 server will bump, the others wont. The only It does not give me an error is just on 1 server.

**Comment by valkyrienyanko** [comment] 2020-10-06 01:47
Showing the error message could be useful.

**Comment by valkyrienyanko** [comment] 2020-10-06 01:55
Possible duplicate of #17

**Closed** 2020-10-06 07:01 UTC
Labels: bug, duplicate
